{% set name = "azure-common" %}
{% set version = "1.1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-common-{{ version }}.zip
  sha256: b2866238aea5d7492cfb0282fc8b8d5f6d06fb433872345864d45753c10b6e4f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - azure.common
    - azure.profiles
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  summary: Microsoft Azure Client Library for Python (Common)
  license_file: LICENSE.txt
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://docs.microsoft.com/en-us/azure/developer/python/

extra:
  recipe-maintainers:
    - Maxyme
    - xylar
