{% set name = "azure-common" %}
{% set version = "1.1.20" %}
{% set sha256 = "76e5b85074e25613ad698db2b02f88ed2c43b2fe56d11e03588a6f6e6f5b4d5a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - azure-nspkg
  run:
    - python
    - azure-nspkg

test:
  imports:
    - azure
    - azure.common
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Client Libraries for Python'

extra:
  recipe-maintainers:
    - ivoflipse
    - Maxyme
