travis:
  secure:
    BINSTAR_TOKEN: rN+WMgDr8UGH1TRNP+2tDpyc4i5RtT2SJH2aHO0aATV5OLEGD11xYO5XUruayTdPMzhhmrFED9jvzpHiUo2fji5GidZ3h7nvaCQgHYrQmPPYK+xbRN+zdVF7aGy/DEOABUyk9YkUpLT45jmmHlTknNRGFP4GeUih3PDGrg2f+KXilCpLrlF6io3cW1NDKnbG90ND3oBMvHRcZh4SSCYxUvUjnXd0kYTviuch/jYUT7A3E5Z/IoZqEfF+Oh8RfJwW8x8wRw+TNMDdcQPa+oPY2sK5CidqP01bvlBWW8jCG3/j/3i1cWPp+HbxiR9WyimzbK/JJJGB1REA7c4eV3bqa6LKWyjSSkkgPXaFHH6zUGSOsdDuM0CqrlI2QSxEuvfPXVuomd12W9hly4ae0UB7981yTmIviKTJtVPAMf9KiDN8upze6b6j5IRcG7Q+2q+VEUuVSYezOXQxbhe6+MVUWQu9WbBc0iApQGJGqSFlq+LYEMxqeEubfMlLkUByM7X40AXS9ofUg9UgrAxThxRRLQ4+EjKRWka+VSw2dZxFVspaEwPcaSNAzmadHkiEXxyDNykD5hivo9pGXw/j1faEAUBlRULDLUY8Y1qu7g4jvaxwpK7kJONcVsoUMMmLah6Ud+YujcarG20dk84ZORzR84hEGdHLEopDx3NInEGD190=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
