travis:
  secure:
    BINSTAR_TOKEN: Ho+8GpkN46ZwHlcJLbshXJUBYMRwe9o/40giWuruuhLS7ZkoC1WIfLKlGuBnEjG7D5Jv2p1VC2AMJd3GHgFfjXrn//eBWv1HrLguJEAObTPqqFVGoE2r9a1nHNzA/pg/ZxQtucrr44CKy7qFqBHGw+cuPuvqaL2f9xdwFLJxv+IXcJ0VIEbABejv1vlQrkEicOKHG5Bzo/kqwbt3XAW+DrllJg2L3uIW9AJiFqhVsKwSdYA4pI7pnM8DxJKx8UwjDBe11Ogalv8vdnq7+2TtEnZTaYKy+cO4N0g4SHTZQelU2o29vxA7yPNKKOQrYsudTPocS3He+5/CklQ1P8RNk4ARhcH4tH8Vwh3lcPrRO82/nqmDsR/s8xEnbc08GBb7LCmhdmli47QyQz3cg4hUJaYJKmpZPwWYY9qYkX92x0JdUzQ+CJFqn7/5Pch0XHPRlDmSn0SClRnSfyHPgtWlAvoJTpgX1AymCighk6hVuRFpiTcaHjZWsjM9v+FD68w1YbWfo7vB1SqtF5oLX3SwjHglvWuRdo3zVQuymtHSqPj8GcbUs9T7SiGaKaNXub/GNxmDBSBFDtsgOOsViDHQf3EPEr1OFIh7TRZXaH/1M104KSNNXyWMRyQT14ELtYxu8967vM0RGFBIQh4u3aOjB0uprecO3OeDz64WJKnKUho=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
